// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:78658c00-a3a9-4335-b9a2-012e558d95ad",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_9evoBmRa5",
    "aws_user_pools_web_client_id": "1naprqnmpul6lh7797tmaub4oh"
};


export default awsmobile;
